remote_theme: rundocs/jekyll-rtd-theme

title: [Cybertek School SDET Program EU4 Batch]
description: [This is a repository for java classes]

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: java
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true